{{- if and .Values.api.enabled .Values.api.route .Values.api.route.enabled }}
{{- $svcName := include "api.fullname" . -}}
{{- $defaultSvcPort := 80 -}}
{{- if and .Values.api.service .Values.api.service.ports (gt (len .Values.api.service.ports) 0) -}}
{{- $defaultSvcPort = (index .Values.api.service.ports 0).port | default 80 -}}
{{- end -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $svcName }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
  {{- if .Values.api.route.annotations }}
  annotations:
    {{- tpl (toYaml .Values.api.route.annotations) $ | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ default "openshift-default" .Values.api.route.className }}
  rules:
    - host: {{ tpl (default (printf "%s.%s" $svcName .Values.global.domain) (printf "%v" .Values.api.route.host)) $ | quote }}
      http:
        paths:
          - path: "/"
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ $svcName }}
                port:
                  number: {{ $defaultSvcPort }}
{{- end }}
