{{- if .Values.api.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: {{ default "ClusterIP" .Values.api.service.type }}
  ports:
    {{- range $p := .Values.api.service.ports }}
    - name: {{ default "http" $p.name }}
      port: {{ $p.port }}
      targetPort: {{ $p.targetPort }}
      protocol: {{ default "TCP" $p.protocol }}
    {{- end }}
  selector:
    {{- include "api.selectorLabels" . | nindent 4 }}
{{- end }}