{{- if and .Values.database.enabled .Values.database.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "database.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
spec:
  type: {{ default "ClusterIP" .Values.database.service.type }}
  selector:
    {{- include "database.selectorLabels" . | nindent 4 }}
  ports:
    {{- range $p := .Values.database.service.ports }}
    - name: {{ default "mongo" $p.name }}
      port: {{ $p.port }}
      targetPort: {{ $p.targetPort }}
      protocol: {{ default "TCP" $p.protocol }}
    {{- end }}
{{- end }}
