{{- if .Values.database.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "database.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "database.fullname" . }}
  replicas: {{ default 1 .Values.database.autoscaling.minReplicas }}
  selector:
    matchLabels:
      {{- include "database.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "database.labels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      {{- if .Values.database.initContainers }}
      initContainers:
        {{- range $ic := .Values.database.initContainers }}
        - name: {{ $ic.name }}
          image: "{{- if and $ic.registry $ic.repository -}}{{ tpl $ic.registry $ }}/{{ tpl $ic.repository $ }}/{{ tpl $ic.image $ }}{{- else if $ic.registry -}}{{ tpl $ic.registry $ }}/{{ tpl $ic.image $ }}{{- else -}}{{ tpl $ic.image $ }}{{- end -}}{{- if $ic.tag -}}:{{ tpl (printf "%v" $ic.tag) $ }}{{- end -}}"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          {{- if $ic.command }}
          command:
            {{- tpl (toYaml $ic.command) $ | nindent 12 }}
          {{- end }}
          {{- if $ic.args }}
          args:
            {{- tpl (toYaml $ic.args) $ | nindent 12 }}
          {{- end }}
          {{- if $ic.resources }}
          resources:
            {{- toYaml $ic.resources | nindent 12 }}
          {{- end }}
          {{- if $ic.volumeMounts }}
          volumeMounts:
            {{- tpl (toYaml $ic.volumeMounts) $ | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}

      containers:
        {{- range $c := .Values.database.containers }}
        - name: {{ $c.name }}
          image: "{{- if and $c.registry $c.repository -}}{{ tpl $c.registry $ }}/{{ tpl $c.repository $ }}/{{ tpl $c.image $ }}{{- else if $c.registry -}}{{ tpl $c.registry $ }}/{{ tpl $c.image $ }}{{- else -}}{{ tpl $c.image $ }}{{- end -}}{{- if $c.tag -}}:{{ tpl (printf "%v" $c.tag) $ }}{{- end -}}"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          {{- if and $c.envFrom $c.envFrom.secretRef $c.envFrom.secretRef.name }}
          envFrom:
            - secretRef:
                name: {{ tpl $c.envFrom.secretRef.name $ }}
          {{- end }}
          {{- if $c.ports }}
          ports:
            {{- tpl (toYaml $c.ports) $ | nindent 12 }}
          {{- end }}
          {{- if $c.resources }}
          resources:
            {{- toYaml $c.resources | nindent 12 }}
          {{- end }}
          {{- if $c.readinessProbe }}
          readinessProbe:
            {{- toYaml $c.readinessProbe | nindent 12 }}
          {{- end }}
          {{- if $c.livenessProbe }}
          livenessProbe:
            {{- toYaml $c.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if $c.volumeMounts }}
          volumeMounts:
            {{- tpl (toYaml $c.volumeMounts) $ | nindent 12 }}
          {{- end }}
        {{- end }}

      {{- if .Values.database.volumes }}
      volumes:
        {{- tpl (toYaml .Values.database.volumes) $ | nindent 8 }}
      {{- end }}

      {{- with .Values.database.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.database.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.database.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
